### ISSUE TITLE
How to compile it on Ubuntu 14.04

### ISSUE THREAD

**Issue by zburgermeiszter** [kiran-geon/node-mjpeg-streamer#1]
I'm trying to compile it on Ubuntu 14.04

Linux 3.13.0-71-generic
node 4.2.4
npm  v2.14.12

I executed the following commands
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
apt-get install -y nodejs
apt-get install -y build-essential
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get update -y
apt-get install -y gcc-4.9 g++-4.9
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

sudo aptitude install -y linux-libc-dev libswscale-dev libboost-dev
cd /tmp
rm -rf /usr/bin/cpp
ln -s /usr/bin/cpp-4.9 /usr/bin/cpp

apt-get install v4l-utils 
npm install --unsafe-perm --save mjpeg-streamer

It fails with the following:
[npm-error.txt](https://github.com/kiran-geon/node-mjpeg-streamer/files/72744/npm-error.txt)
[npm-debug.log.txt](https://github.com/kiran-geon/node-mjpeg-streamer/files/72743/npm-debug.log.txt)

If I missed anything please let me know.

Thanks.

**Comment by kiran-geon** [comment]
Hi Zoltan,

I could see that the error is occuring during "v4l2camera" module  compilation.

Can you please try compiling "v4l2camera" independantly?

**Comment by zburgermeiszter** [comment]
I can compile v4l2camera NPM module by running the following commands:

apt-get install -y build-essential
add-apt-repository -y ppa:ubuntu-toolchain-r/test
apt-get update -y
apt-get install -y gcc-4.9 g++-4.9
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
npm install --save v4l2camera

It install and compile v4lcamera with the following result.
[npm-result-v4l2camera.txt](https://github.com/kiran-geon/node-mjpeg-streamer/files/73819/npm-result-v4l2camera.txt)

Also reinstalled node from source, but it still fails at the "jpeg" package.
https://www.digitalocean.com/community/tutorials/how-to-install-an-upstream-version-of-node-js-on-ubuntu-12-04

**Comment by kiran-geon** [comment]
I could see that when you install "v4l2camera" independently, the v4l2camera version getting installed is 1.0.2. But I have only tested with  v4l2camera version  0.4.3 and that is the version which will be fetched from npm when you install mjpeg-streamer.  You can modify the package.json and try running mjpeg-streamer with v4l2camera 1.0.2. I am not in a position to test this now.

**Comment by zburgermeiszter** [comment]
Thanks,
I modified the package.json to use v4l2camera@1.0.2, it gives less errors.

Only this one which prevents me compiling the jpeg module:
npm WARN cannot run in wd jpeg@2.0.0 node-gyp configure build (wd=/tmp/node-mjpeg-streamer/node_modules/jpeg)

I'll keep googling.

If I managed to compile it I'll send a pull request.

Thanks.

**Comment by zburgermeiszter** [comment]
Pull request sent: https://github.com/kiran-geon/node-mjpeg-streamer/pull/2
